out_prefix: 'my-test'
var_list: 'test_var.txt'
pred_model:
  path: '/project2/xinhe/DeepVariantAnnotation/models/deepsea_ATAC053018.hdf5'
  label:
    l1: 1
    l2: 2
reference_genome: '/project2/xinhe/yanyul/databases/hg19/hg19.fa'


##### some default setup #####
#### usually don't change ####
check_allele: True
design: '499-1-500'
##############################
##############################
