out_prefix: 'zhongshan_dnm-atac053018'
var_list: '/project2/xinhe/zhongshan/forDeepSea/Yuen_Simons_DNM_comb.bed'
pred_model:
  path: '/scratch/midway2/xinhe/repo/deep_variant/train_deepsea/model/DeepSEA-ATAC053018_logistic.best.hdf5'
  label:
    CN: 1
    DN: 2
    GA: 3
    ips: 4
    NSC: 5
reference_genome: '/project2/xinhe/yanyul/databases/hg19/hg19.fa'


##### some default setup #####
#### usually don't change ####
check_allele: True
design: '499-1-500'
##############################
##############################
